project_id = "qyblzbqpyasfoirqzdpo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.fetch-youtube-streams]
verify_jwt = false

[functions.fetch-youtube-streams.secrets]
YOUTUBE_API_KEY = ""

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook.secrets]
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""